# Generated by Django 5.1 on 2024-10-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_blog_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank='true', default='default.png', upload_to='images/'),
        ),
    ]
